excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://BradEvoy.github.io
title: Towers Other Than Ivory
tagline: Activism, Policy, and Things.
description: The one and only blog of relative nobody, Brad Evoy.
paginate: 5